import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <body className="bg-gray-800">
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>
        {/* Center of the page */}
        <div className="flex flex-col items-center justify-center h-screen">
          <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
            <h1 className="font-bold text-4xl">OLLI WESSELINGH</h1>
          </div>
        </div>
      </main>
    </div>
    </body>
  )
}
